"""
Static analysis of a parsed program.

Produces three kinds of messages (§2.6 of the brief):

1. Conflict — an action identifier is produced by two or more rules.
       Action <id> generated by r1, r2, ...

2. Redundancy — two rules with identical condition AND identical
   action exist. Conditions are compared modulo AND-commutativity
   (using `canonical_cond_key` from ast_nodes): `a AND b` and `b AND a`
   are redundant. Repeated atoms are also collapsed (`a AND a` matches
   `a`).
       Redundant rules: r1, r2

3. Potentially inactive rule — heuristic for rules that "stand out"
   as problematic relative to the rest of the program. A rule is
   flagged iff:

       (a) it contains at least one comparison whose variable is
           undefined or whose comparison is falsified by the initial
           state, AND
       (b) its action identifier is not used as a fact reference in
           any rule's condition (i.e. it is a "leaf" action that can
           never feed another rule), AND
       (c) the program contains at least one OTHER rule whose
           comparisons are all satisfied (or which has no comparisons
           at all) — i.e. a "live" rule that could plausibly fire.

   Condition (c) prevents flagging a single-rule program or a program
   where every rule is equally problematic (case 3 and case 7), and
   ensures we only flag rules that "stand out" against an otherwise
   functional rule set (case 8: r2 has no comparisons so it's live;
   r3 has a falsified comparison and a leaf action so it stands out).

       Potentially inactive rule: <id>

Output ordering:
- Conflicts come first, in the order their action's first-producing
  rule was defined.
- Redundancies come next, in the order of the first rule of each
  redundant group.
- Inactive-rule messages come last, in definition order of the rules.
"""

from __future__ import annotations

from collections import OrderedDict
from typing import Dict, List, Set, Tuple

from .ast_nodes import (
    Comparison,
    Cond,
    Fact,
    Program,
    Rule,
    canonical_cond_key,
    flatten_and,
)


# --- Tree-walking helpers (built on top of `flatten_and`) -------------------


def _comparisons(cond: Cond) -> List[Comparison]:
    """All `Comparison` atoms inside a condition tree."""
    return [a for a in flatten_and(cond) if isinstance(a, Comparison)]


def _condition_referenced_idents(cond: Cond) -> List[str]:
    """Idents that appear as `Fact` references inside a condition."""
    return [a.ident for a in flatten_and(cond) if isinstance(a, Fact)]


def _comparison_is_falsified(c: Comparison, vars_: Dict[str, int]) -> bool:
    """True iff the comparison's variable is undefined or the
    comparison is false under the initial state."""
    if c.ident not in vars_:
        return True
    x = vars_[c.ident]
    if c.op == ">":
        return not (x > c.value)
    if c.op == "<":
        return not (x < c.value)
    if c.op == "=":
        return not (x == c.value)
    raise ValueError(f"unknown comparison operator: {c.op!r}")


# --- Main entry point -------------------------------------------------------


def analyze(program: Program, vars_: Dict[str, int]) -> List[str]:
    """Return the list of static-analysis messages for `program`.

    `vars_` is the initial variable map from the State block. It's used
    only by the inactive-rule check.
    """
    msgs: List[str] = []

    # Precompute the (cond_key, action) -> rules grouping. We use this
    # for both redundancy detection AND for deciding whether to suppress
    # a conflict that's already fully explained by a redundancy.
    groups: "OrderedDict[Tuple[Tuple, str], List[str]]" = OrderedDict()
    for rule in program.rules:
        key = (canonical_cond_key(rule.cond), rule.action.ident)
        groups.setdefault(key, []).append(rule.name)

    # ---- 1. Conflict detection -----------------------------------------
    #
    # An action is in conflict iff it's produced by rules in at least
    # two *distinct* (cond_key, action) groups. If all producing rules
    # are in one group, they're identical (pure redundancy) and the
    # redundancy message alone captures the situation — see test
    # case 7, where the PDF shows only "Redundant rules: r1, r2" and
    # no conflict.
    action_to_rules: "OrderedDict[str, List[str]]" = OrderedDict()
    action_to_groups: Dict[str, Set[Tuple]] = {}
    for rule in program.rules:
        action_to_rules.setdefault(rule.action.ident, []).append(rule.name)
        action_to_groups.setdefault(rule.action.ident, set()).add(
            canonical_cond_key(rule.cond)
        )
    for action, rules_with_action in action_to_rules.items():
        if len(rules_with_action) >= 2 and len(action_to_groups[action]) >= 2:
            msgs.append(
                f"Action {action} generated by {', '.join(rules_with_action)}"
            )

    # ---- 2. Redundancy detection ---------------------------------------
    #
    # Any group with >= 2 rules emits one message listing them in
    # definition order.
    for _, rules_in_group in groups.items():
        if len(rules_in_group) >= 2:
            msgs.append(f"Redundant rules: {', '.join(rules_in_group)}")

    # ---- 3. Potentially-inactive-rule detection ------------------------
    #
    # An action is a "consumed" identifier if any rule references it as
    # a Fact inside its condition. A rule is "live" if none of its
    # comparisons are falsified (vacuously true if it has no
    # comparisons). A rule R is flagged when:
    #   - R has at least one falsified comparison, AND
    #   - R's action is not consumed by any rule's condition, AND
    #   - there exists some other rule that is "live".
    #
    # The third clause prevents flagging single-rule programs (case 3)
    # and programs where every rule has the same problem (case 7).
    consumed_idents: Set[str] = set()
    for rule in program.rules:
        consumed_idents.update(_condition_referenced_idents(rule.cond))

    def _is_live(rule: Rule) -> bool:
        """A rule is "live" if none of its comparisons are falsified."""
        return not any(_comparison_is_falsified(c, vars_) for c in _comparisons(rule.cond))

    has_live_rule = any(_is_live(r) for r in program.rules)

    for rule in program.rules:
        comps = _comparisons(rule.cond)
        if not comps:
            continue
        if not any(_comparison_is_falsified(c, vars_) for c in comps):
            continue
        if rule.action.ident in consumed_idents:
            continue
        # A rule with a falsified comparison is never "live" itself,
        # so any live rule is automatically a *different* rule.
        if has_live_rule:
            msgs.append(f"Potentially inactive rule: {rule.name}")

    return msgs
